[package]
name = "tus_client"
version = "0.1.0"
authors = ["Jon Grythe Stødle <jonstodle@outlook.com>"]
edition = "2018"

[dependencies]
base64 = "0.10"

[dev-dependencies]
tempfile = "3.1.0"
rand = "0.7.0"
